---
os: linux
dist: xenial

language: python
python:
  - "3.7"

install:
  - pip install -e .[dev]
script:
  - yapf --quiet --recursive .
  - python3 -m pytest -sv --cov=rxn_utilities --cov-fail-under=60
  - python3 -m flake8 --disable-noqa .
  - mypy rxn_utilities

deploy:
  provider: pypi
  server: https://${PYPI_SERVER}
  distributions: "sdist bdist_wheel"
  username: ${PYPI_USERNAME}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
