---
os: linux
dist: xenial

language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install -e .[dev]
script:
  - yapf --quiet --recursive .
  - python3 -m pytest -sv --cov=rxn_utilities --cov-fail-under=60
  - python3 -m flake8 --disable-noqa .
  - mypy rxn_utilities

deploy:
  provider: pypi
  server: https://eu.artifactory.swg-devops.com/artifactory/api/pypi/res-accelerated-discovery-team-rxn-private-pypi-local
  distributions: "sdist bdist_wheel"
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  on:
    tags: true
